spring.application.name=lextech

# Servidor
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lextech
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true