spring.application.name=lextech

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lextech
spring.datasource.username=postgres
spring.datasource.password=1234

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=8080